/*
 * This file has been automatically generated by charsets_gen.py.
 * Do not edit it by hand.
 *
 * Definitions of aliases for all the charsets supported by the
 * application, obtained by mixing the IANA charset list [1] and
 * the list of iconv-supported charsets.
 *
 * [1] http://www.iana.org/assignments/character-sets
 *
 */

/* Number of known aliases */
#define CHARSET_ALIAS_NUM 581

/* Positions of aliases for some relevant character sets*/
#define CHARSET_ISO_8859_1 &charset_aliases[358]
#define CHARSET_UTF_8 &charset_aliases[564]
#define CHARSET_UTF_16 &charset_aliases[557]
#define CHARSET_UTF_16BE &charset_aliases[558]
#define CHARSET_UTF_16LE &charset_aliases[559]
#define CHARSET_UCS_4 &charset_aliases[350]
